sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t joel/docker-react-app -f Dockerfile.dev .

script:
  - docker fun -e CI=true joel/docker-react-app npm run test -- --coverage

after_success:
  - echo "test success"